### ISSUE TITLE
Fix bug - Date

### ISSUE THREAD

**Issue by ailsacs** [moreira-thiago/laboratorio_de_dexter#1]
erro apresentado após processamento da fila, as mensagens não estão sendo salvas no banco, devido à incompatibilidade entre o formato de hora.

2023-10-12 13:09:39,094 - root - ERROR - Erro ao salvar mensagem no banco de dados: 1292 (22007): Incorrect time value: '10:08:35 AM' for column 'hora' at row 1

Sistema não aceita formato AM/PM.

**Comment by moreira-thiago** [comment]
Converte hora de dateTime em uma string no formato "HH:MM:SS" (horas, minutos e segundos), garantindo que a hora seja exibida no formato de 24 horas

      // Função para formatar a data e hora no formato correto
      function formatDateTime(dateTime) {
         var day = String(dateTime.getDate()).padStart(2, '0');
         var month = String(dateTime.getMonth() + 1).padStart(2, '0');
         var year = dateTime.getFullYear();
         
         var options = { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' };
         var horaFormatada = dateTime.toLocaleTimeString(undefined, options);
         return day + '/' + month + '/' + year + ' ' + horaFormatada;
      }
      
      
             // Obtenha a data e hora atuais do sistema
            var dataHora = new Date();
            var dataHoraFormatada = formatDateTime(dataHora); // Formate a data e hora
            var data = dataHoraFormatada.split(' ')[0]; 
            var hora = dataHoraFormatada.split(' ')[1];
            var mensagem = "Data: " + data + ", Hora: " + hora + ", UUID: " + mensagemUUID + ", Nome: " + nome;
